<?php
/**
 * Automatic LLMs.txt Generator -- the generator, shared by the storefront and the admin.
 *
 * Everything that reads the catalog and turns it into Markdown lives here, as
 * plain prefixed functions. No namespace, no class, no autoloader: Zen Cart
 * registers PSR-4 plugin paths differently on v1.5.8 and v3.0.0, and no release
 * auto-loads a plugin's storefront function files at all, so every entry point
 * (the page, the init script, the admin page, the observer, the installer)
 * `require_once`s this file by its own __DIR__ path instead.
 *
 * Nothing here echoes and nothing here calls exit(): the functions return
 * strings and arrays, and the thin entry points decide what to do with them.
 * That is also what makes the whole file testable without a web server.
 *
 * Written for PHP 7.4 through 8.5: no match, no nullsafe, no named arguments,
 * no union types, no str_contains(); every parameter that may be null says so.
 *
 * The output follows https://llmstxt.org/ -- one H1, one blockquote summary,
 * optional free text, then H2 sections each holding a list of
 * "- [name](url): notes" lines.
 *
 * @package  LlmsTxt
 * @license  http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 */

if (!defined('IS_ADMIN_FLAG')) {
    die('Illegal Access');
}

if (defined('LLMSTXT_GENERATOR_LOADED')) {
    return;
}
define('LLMSTXT_GENERATOR_LOADED', true);

/**
 * The version this file ships in. Kept in one place so the readme check can
 * compare it with the directory name and the manifest.
 */
define('LLMSTXT_VERSION', 'v1.0.1');

/**
 * Text placed at the very end of every file this plugin writes, so a file at
 * the store root can be recognized as ours even after the state file is gone.
 * An HTML comment is valid Markdown and invisible to renderers.
 */
define('LLMSTXT_MARKER', 'Generated by Automatic LLMs.txt Generator for Zen Cart');

/**
 * How long the storefront waits between two looks at whether a published file
 * is due for a rebuild. Seconds. The check itself is a handful of aggregate
 * queries, so this is about not doing them on every page view, not about cost.
 */
define('LLMSTXT_CHECK_INTERVAL', 900);

/**
 * How long a build lock is honored before it is assumed abandoned. Seconds.
 */
define('LLMSTXT_LOCK_TTL', 120);

/**
 * Fire a notifier event when Zen Cart's notifier is present, and do nothing
 * when it is not (a CLI harness, or a request too early for observers).
 *
 * These are the extension points other plugins may use; the Pro edition of
 * this plugin is one. $param2 is passed by reference, as Zen Cart's own
 * notify() does, so an observer can change it.
 *
 * @param string $event
 * @param mixed  $param1
 * @param mixed  $param2
 */
function llmstxt_notify($event, $param1 = [], &$param2 = null)
{
    global $zco_notifier;
    if (isset($zco_notifier) && is_object($zco_notifier) && method_exists($zco_notifier, 'notify')) {
        $zco_notifier->notify($event, $param1, $param2);
    }
}

/* ------------------------------------------------------------------ *
 * Settings
 * ------------------------------------------------------------------ */

/**
 * A configuration constant, with a default for when it is not defined.
 *
 * The portable form of zen_config(), which is v3.0.0 only.
 *
 * @param string $key
 * @param mixed  $default
 * @return mixed
 */
function llmstxt_cfg($key, $default = '')
{
    return defined($key) ? constant($key) : $default;
}

/**
 * Every setting the generator reads, normalized once.
 *
 * The keys mirror the configuration keys without their prefix. Values are
 * cast here so that nothing below has to re-check a string 'true' or a
 * negative count.
 *
 * @return array
 */
function llmstxt_settings()
{
    $bool = static function ($key, $default) {
        $v = llmstxt_cfg($key, $default ? 'true' : 'false');
        return ((string)$v === 'true' || (string)$v === '1');
    };
    $int = static function ($key, $default) {
        return max(0, (int)llmstxt_cfg($key, $default));
    };
    $choice = static function ($key, array $allowed, $default) {
        $v = strtolower(trim((string)llmstxt_cfg($key, $default)));
        return in_array($v, $allowed, true) ? $v : $default;
    };

    return [
        'enabled' => $bool('LLMSTXT_STATUS', true),
        'output' => $choice('LLMSTXT_OUTPUT', ['file', 'dynamic', 'both'], 'file'),
        'rebuild' => $choice('LLMSTXT_REBUILD', ['change', 'daily', 'weekly', 'monthly', 'manual'], 'change'),
        'summary' => trim((string)llmstxt_cfg('LLMSTXT_SUMMARY', '')),
        'notes' => trim((string)llmstxt_cfg('LLMSTXT_NOTES', '')),
        'language' => strtolower(trim((string)llmstxt_cfg('LLMSTXT_LANGUAGE', ''))),
        'info_pages' => trim((string)llmstxt_cfg('LLMSTXT_INFO_PAGES', 'shippinginfo,privacy,conditions,contact_us,site_map')),
        'categories' => $bool('LLMSTXT_INCLUDE_CATEGORIES', true),
        'category_depth' => $int('LLMSTXT_CATEGORY_DEPTH', 0),
        'exclude_categories' => llmstxt_id_list(llmstxt_cfg('LLMSTXT_EXCLUDE_CATEGORIES', '')),
        'products' => $bool('LLMSTXT_INCLUDE_PRODUCTS', true),
        'max_products' => $int('LLMSTXT_MAX_PRODUCTS', 200),
        'product_order' => $choice('LLMSTXT_PRODUCT_ORDER', ['sort', 'newest', 'bestsellers', 'name', 'viewed'], 'sort'),
        'prices' => $bool('LLMSTXT_INCLUDE_PRICES', true),
        'brands' => $bool('LLMSTXT_INCLUDE_BRANDS', true),
        'ezpages' => $bool('LLMSTXT_INCLUDE_EZPAGES', true),
        'sitemap' => trim((string)llmstxt_cfg('LLMSTXT_SITEMAP_URL', '')),
        'description_length' => max(40, $int('LLMSTXT_DESCRIPTION_LENGTH', 160)),
        'full' => $bool('LLMSTXT_FULL', false),
        'full_length' => max(200, $int('LLMSTXT_FULL_LENGTH', 1200)),
    ];
}

/**
 * "12, 15,3" -> [3, 12, 15]. Anything that is not a positive integer is dropped.
 *
 * @param mixed $text
 * @return int[]
 */
function llmstxt_id_list($text)
{
    $ids = [];
    foreach (preg_split('~[\s,;]+~', (string)$text) as $piece) {
        $n = (int)$piece;
        if ($n > 0) {
            $ids[$n] = $n;
        }
    }
    $ids = array_values($ids);
    sort($ids);
    return $ids;
}

/**
 * A hash of everything that changes the output without the catalog changing.
 * Stored with each build, so editing a setting makes the next check rebuild.
 *
 * @param array|null $settings
 * @return string
 */
function llmstxt_settings_hash($settings = null)
{
    if ($settings === null) {
        $settings = llmstxt_settings();
    }
    return sha1(LLMSTXT_VERSION . '|' . serialize($settings) . '|'
        . (string)llmstxt_cfg('STORE_NAME', '') . '|' . llmstxt_catalog_base() . '|'
        . (string)llmstxt_cfg('DEFAULT_CURRENCY', '') . '|' . (string)llmstxt_cfg('DEFAULT_LANGUAGE', ''));
}

/* ------------------------------------------------------------------ *
 * Paths and URLs
 * ------------------------------------------------------------------ */

/**
 * The store's cache directory, with a trailing slash.
 *
 * DIR_FS_SQL_CACHE is defined by includes/defined_paths.php on every supported
 * release (and by the admin's own copy on v3.0.0), but the fallback is the
 * same value the core would have used, so this cannot come out wrong.
 *
 * @return string
 */
function llmstxt_cache_dir()
{
    $dir = defined('DIR_FS_SQL_CACHE') ? (string)DIR_FS_SQL_CACHE : DIR_FS_CATALOG . 'cache';
    return rtrim($dir, '/\\') . '/';
}

/**
 * Where a published file lives: the store root, next to robots.txt.
 *
 * @param bool $full
 * @return string
 */
function llmstxt_file_path($full = false)
{
    return DIR_FS_CATALOG . ($full ? 'llms-full.txt' : 'llms.txt');
}

/**
 * Where the dynamic page's rendered copy is kept between builds.
 *
 * @param bool $full
 * @return string
 */
function llmstxt_cache_path($full = false)
{
    return llmstxt_cache_dir() . ($full ? 'llms_txt.full.cache.txt' : 'llms_txt.cache.txt');
}

function llmstxt_state_path()
{
    return llmstxt_cache_dir() . 'llms_txt.state.json';
}

/**
 * The storefront's base URL with a trailing slash, from whichever side is
 * running. The admin's configure.php names the storefront with the
 * *_CATALOG_SERVER constants; the storefront's names it with HTTP_SERVER.
 *
 * https is preferred whenever the store says it has it, because that is the
 * address a crawler should be given.
 *
 * @return string
 */
function llmstxt_catalog_base()
{
    if (defined('IS_ADMIN_FLAG') && IS_ADMIN_FLAG === true && defined('HTTP_CATALOG_SERVER')) {
        $ssl = (llmstxt_cfg('ENABLE_SSL_CATALOG', 'false') === 'true' && defined('HTTPS_CATALOG_SERVER') && HTTPS_CATALOG_SERVER !== '');
        $server = $ssl ? (string)HTTPS_CATALOG_SERVER : (string)HTTP_CATALOG_SERVER;
        $dir = defined('DIR_WS_CATALOG') ? (string)DIR_WS_CATALOG : '/';
    } else {
        $ssl = (llmstxt_cfg('ENABLE_SSL', 'false') === 'true' && defined('HTTPS_SERVER') && HTTPS_SERVER !== '');
        $server = $ssl ? (string)HTTPS_SERVER : (string)llmstxt_cfg('HTTP_SERVER', '');
        $dir = defined('DIR_WS_CATALOG') ? (string)DIR_WS_CATALOG : '/';
    }
    return rtrim($server, '/') . '/' . ltrim($dir, '/');
}

/**
 * A storefront URL for a page.
 *
 * On the storefront, zen_href_link() is used so that an SEO-URL plugin, which
 * overrides that function, gets to shape the address exactly as it does for
 * every other link on the site. No session id is ever added.
 *
 * In the admin, zen_href_link() builds ADMIN addresses, so the storefront form
 * is assembled by hand. A store running an SEO-URL plugin therefore gets plain
 * index.php addresses from an admin-triggered build and SEO addresses from a
 * storefront-triggered one; both resolve, and the readme says so.
 *
 * @param string $page   a main_page name
 * @param string $params query-string without the leading ?
 * @return string
 */
function llmstxt_link($page, $params = '')
{
    $page = (string)$page;
    $params = (string)$params;

    $inAdmin = (defined('IS_ADMIN_FLAG') && IS_ADMIN_FLAG === true);
    if (!$inAdmin && function_exists('zen_href_link')) {
        // zen_href_link() returns an address ready to sit in an HTML
        // attribute, so its parameter separator is &amp;. This is a text file.
        return html_entity_decode((string)zen_href_link($page, $params, 'NONSSL', false), ENT_QUOTES, 'UTF-8');
    }

    $url = llmstxt_catalog_base() . 'index.php?main_page=' . rawurlencode($page);
    if ($params !== '') {
        $url .= '&' . $params;
    }
    return $url;
}

/* ------------------------------------------------------------------ *
 * Text helpers
 * ------------------------------------------------------------------ */

/**
 * HTML -> one line of plain text, cut at a word boundary.
 *
 * Block-level tags become spaces first so "<p>One</p><p>Two</p>" does not read
 * "OneTwo". Entities are decoded, whitespace is collapsed, and a cut is marked
 * with a single ellipsis character.
 *
 * @param mixed $html
 * @param int   $maxLength  0 = no cut
 * @return string
 */
function llmstxt_text($html, $maxLength = 0)
{
    $text = (string)$html;
    $text = preg_replace('~<\s*(script|style)\b[^>]*>.*?<\s*/\s*\1\s*>~is', ' ', $text);
    $text = preg_replace('~<\s*(br|/p|/div|/li|/h[1-6]|/tr|/td|/th)\b[^>]*>~i', ' ', $text);
    $text = strip_tags($text);
    $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $text = str_replace(["\xC2\xA0", "\xE2\x80\x8B"], ' ', $text);
    $text = preg_replace('~\s+~u', ' ', $text);
    $text = trim((string)$text);

    if ($maxLength > 0 && llmstxt_strlen($text) > $maxLength) {
        $cut = llmstxt_substr($text, 0, $maxLength);
        $space = strrpos($cut, ' ');
        if ($space !== false && $space > (int)($maxLength * 0.6)) {
            $cut = substr($cut, 0, $space);
        }
        $text = rtrim($cut, " \t,;:-") . "\xE2\x80\xA6";
    }

    return $text;
}

/**
 * Multibyte-safe length and substring, without requiring ext/mbstring.
 */
function llmstxt_strlen($s)
{
    return function_exists('mb_strlen') ? mb_strlen($s, 'UTF-8') : strlen($s);
}

function llmstxt_substr($s, $start, $length)
{
    return function_exists('mb_substr') ? mb_substr($s, $start, $length, 'UTF-8') : substr($s, $start, $length);
}

/**
 * Backslash-escape the characters that carry meaning inside a Markdown line,
 * so a product called "50% off [Sale]" or "Model_K *new*" reads as written
 * instead of turning into a link, emphasis or a tag. Only inline syntax is
 * covered: "-", "#" and ">" matter at the start of a line, and nothing that
 * passes through here ever starts one. CommonMark treats a backslash before
 * any ASCII punctuation as the literal character, so the escapes are safe
 * whichever parser reads the file.
 *
 * @param mixed $s
 * @return string
 */
function llmstxt_escape($s)
{
    return str_replace(
        ['\\', '`', '*', '_', '[', ']', '<'],
        ['\\\\', '\\`', '\\*', '\\_', '\\[', '\\]', '\\<'],
        (string)$s
    );
}

/**
 * Text that will sit inside [ ] as a link label or after "# " as a heading:
 * one line, Markdown-escaped.
 *
 * @param mixed $s
 * @return string
 */
function llmstxt_label($s)
{
    return llmstxt_escape(trim(str_replace(["\r", "\n"], ' ', (string)$s)));
}

/**
 * A URL that is safe to sit inside ( ). Spaces and parentheses are the two
 * things that break Markdown link syntax.
 *
 * @param mixed $url
 * @return string
 */
function llmstxt_url($url)
{
    return str_replace([' ', '(', ')'], ['%20', '%28', '%29'], trim((string)$url));
}

/**
 * One "- [label](url): notes" line, or "- [label](url)" when there are no notes.
 *
 * @param string $label
 * @param string $url
 * @param string $notes
 * @return string
 */
function llmstxt_item($label, $url, $notes = '')
{
    $line = '- [' . llmstxt_label($label) . '](' . llmstxt_url($url) . ')';
    $notes = llmstxt_escape(trim(str_replace(["\r", "\n"], ' ', (string)$notes)));
    if ($notes !== '') {
        $line .= ': ' . $notes;
    }
    return $line;
}

/**
 * A price for the listing, in the store's default currency.
 *
 * Formatted from the currencies table rather than the storefront's $currencies
 * object, which does not exist in the admin. The tax-free base price is used:
 * a file read by a machine is better off with the unambiguous figure.
 *
 * @param float      $price
 * @param array|null $currency  row from llmstxt_default_currency()
 * @return string
 */
function llmstxt_format_price($price, $currency)
{
    $price = (float)$price;
    if (!is_array($currency)) {
        return number_format($price, 2, '.', '');
    }
    $decimals = (int)$currency['decimal_places'];
    $formatted = number_format(
        $price * (float)$currency['value'],
        $decimals,
        (string)$currency['decimal_point'],
        (string)$currency['thousands_point']
    );
    return (string)$currency['symbol_left'] . $formatted . (string)$currency['symbol_right'];
}

/* ------------------------------------------------------------------ *
 * Reading the catalog
 * ------------------------------------------------------------------ */

/**
 * The language the file is written in: the configured code, else the store
 * default, else languages_id 1.
 *
 * @param object $db
 * @param array  $settings
 * @return int
 */
function llmstxt_language_id($db, array $settings)
{
    $codes = [];
    if ($settings['language'] !== '') {
        $codes[] = $settings['language'];
    }
    $default = strtolower((string)llmstxt_cfg('DEFAULT_LANGUAGE', 'en'));
    if ($default !== '' && !in_array($default, $codes, true)) {
        $codes[] = $default;
    }

    foreach ($codes as $code) {
        $r = $db->Execute(
            "SELECT languages_id FROM " . TABLE_LANGUAGES . "
              WHERE code = '" . $db->prepare_input($code) . "'
              LIMIT 1"
        );
        if (!$r->EOF) {
            return (int)$r->fields['languages_id'];
        }
    }
    return 1;
}

/**
 * The default currency's formatting row, or null if it cannot be found.
 *
 * @param object $db
 * @return array|null
 */
function llmstxt_default_currency($db)
{
    $code = (string)llmstxt_cfg('DEFAULT_CURRENCY', '');
    if ($code === '') {
        return null;
    }
    $r = $db->Execute(
        "SELECT code, symbol_left, symbol_right, decimal_point, thousands_point, decimal_places, value
           FROM " . TABLE_CURRENCIES . "
          WHERE code = '" . $db->prepare_input($code) . "'
          LIMIT 1"
    );
    if ($r->EOF) {
        return null;
    }
    $row = $r->fields;
    $row['value'] = ((float)$row['value'] > 0) ? (float)$row['value'] : 1.0;
    return $row;
}

/**
 * Every category, keyed by id, with its name, description, parent, status and
 * sort order. One query, then the tree is walked in PHP.
 *
 * @param object $db
 * @param int    $languageId
 * @return array
 */
function llmstxt_read_categories($db, $languageId)
{
    $rows = [];
    $r = $db->Execute(
        "SELECT c.categories_id, c.parent_id, c.sort_order, c.categories_status,
                cd.categories_name, cd.categories_description
           FROM " . TABLE_CATEGORIES . " c
                LEFT JOIN " . TABLE_CATEGORIES_DESCRIPTION . " cd
                    ON cd.categories_id = c.categories_id
                   AND cd.language_id = " . (int)$languageId . "
          ORDER BY c.parent_id, c.sort_order, cd.categories_name"
    );
    while (!$r->EOF) {
        $id = (int)$r->fields['categories_id'];
        $rows[$id] = [
            'id' => $id,
            'parent' => (int)$r->fields['parent_id'],
            'name' => (string)$r->fields['categories_name'],
            'description' => (string)$r->fields['categories_description'],
            'status' => ((int)$r->fields['categories_status'] === 1),
            'sort' => (int)$r->fields['sort_order'],
        ];
        $r->MoveNext();
    }
    return $rows;
}

/**
 * Walk the category tree and return the ones to list, in tree order, each
 * with its full path ("Hardware > Cables") and depth.
 *
 * A category is listed only when it and every ancestor are enabled, none of
 * them is excluded, and it has a name. `category_depth` 0 means every level.
 *
 * The returned 'visible' set (every listable category, regardless of the
 * depth cut) is what product selection uses, so a product is listed only when
 * its master category would be reachable on the storefront.
 *
 * @param array $categories  from llmstxt_read_categories()
 * @param array $settings
 * @return array  ['list' => [...], 'visible' => [id => true]]
 */
function llmstxt_category_tree(array $categories, array $settings)
{
    $children = [];
    foreach ($categories as $id => $c) {
        $children[$c['parent']][] = $id;
    }
    $excluded = array_flip($settings['exclude_categories']);
    $maxDepth = (int)$settings['category_depth'];

    $list = [];
    $visible = [];

    $walk = static function ($parent, $path, $depth) use (&$walk, &$list, &$visible, $children, $categories, $excluded, $maxDepth) {
        if (empty($children[$parent])) {
            return;
        }
        $ids = $children[$parent];
        usort($ids, static function ($a, $b) use ($categories) {
            if ($categories[$a]['sort'] !== $categories[$b]['sort']) {
                return $categories[$a]['sort'] <=> $categories[$b]['sort'];
            }
            return strcasecmp($categories[$a]['name'], $categories[$b]['name']);
        });
        foreach ($ids as $id) {
            $c = $categories[$id];
            if (!$c['status'] || isset($excluded[$id]) || trim($c['name']) === '') {
                continue;
            }
            $fullPath = ($path === '') ? $c['name'] : $path . ' > ' . $c['name'];
            $visible[$id] = true;
            if ($maxDepth === 0 || $depth <= $maxDepth) {
                $list[] = [
                    'id' => $id,
                    'name' => $c['name'],
                    'path' => $fullPath,
                    'depth' => $depth,
                    'description' => $c['description'],
                ];
            }
            $walk($id, $fullPath, $depth + 1);
        }
    };
    $walk(0, '', 1);

    return ['list' => $list, 'visible' => $visible];
}

/**
 * The products to list, already filtered to those a shopper could reach.
 *
 * The meta-tag description is preferred over the body text when the owner has
 * written one, because it is the sentence they chose to describe the product
 * to a machine.
 *
 * @param object $db
 * @param int    $languageId
 * @param array  $settings
 * @param array  $visibleCategories  [id => true]
 * @return array
 */
function llmstxt_read_products($db, $languageId, array $settings, array $visibleCategories)
{
    switch ($settings['product_order']) {
        case 'newest':
            $order = 'p.products_date_added DESC, pd.products_name';
            break;
        case 'bestsellers':
            $order = 'p.products_ordered DESC, pd.products_name';
            break;
        case 'name':
            $order = 'pd.products_name';
            break;
        case 'viewed':
            $order = 'pd.products_viewed DESC, pd.products_name';
            break;
        default:
            $order = 'p.products_sort_order, pd.products_name';
    }

    $products = [];
    $r = $db->Execute(
        "SELECT p.products_id, p.products_model, p.products_price, p.master_categories_id,
                p.products_type, pt.type_handler,
                pd.products_name, pd.products_description,
                mt.metatags_description
           FROM " . TABLE_PRODUCTS . " p
                LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd
                    ON pd.products_id = p.products_id
                   AND pd.language_id = " . (int)$languageId . "
                LEFT JOIN " . TABLE_META_TAGS_PRODUCTS_DESCRIPTION . " mt
                    ON mt.products_id = p.products_id
                   AND mt.language_id = " . (int)$languageId . "
                LEFT JOIN " . TABLE_PRODUCT_TYPES . " pt
                    ON pt.type_id = p.products_type
          WHERE p.products_status = 1
          ORDER BY " . $order
    );

    $limit = (int)$settings['max_products'];
    while (!$r->EOF) {
        $master = (int)$r->fields['master_categories_id'];
        $name = trim((string)$r->fields['products_name']);
        if ($name !== '' && ($master === 0 || isset($visibleCategories[$master]))) {
            $handler = trim((string)$r->fields['type_handler']);
            $products[] = [
                'id' => (int)$r->fields['products_id'],
                'name' => $name,
                'model' => trim((string)$r->fields['products_model']),
                'price' => (float)$r->fields['products_price'],
                'category' => $master,
                'page' => ($handler !== '' ? $handler : 'product') . '_info',
                'description' => (string)$r->fields['products_description'],
                'meta' => trim((string)$r->fields['metatags_description']),
            ];
            if ($limit > 0 && count($products) >= $limit) {
                break;
            }
        }
        $r->MoveNext();
    }
    return $products;
}

/**
 * Manufacturers ("brands") with at least one enabled product, in name order,
 * each with its product count. Products in hidden or excluded categories are
 * not counted, so a brand whose only products sit in an excluded category is
 * left out, as the products themselves are. The link is the manufacturer
 * listing on the index page, which every release serves.
 *
 * @param object $db
 * @param array  $visibleCategories  id => true, from llmstxt_category_tree()
 * @return array
 */
function llmstxt_read_brands($db, array $visibleCategories)
{
    $brands = [];
    $r = $db->Execute(
        "SELECT m.manufacturers_id, m.manufacturers_name, p.master_categories_id
           FROM " . TABLE_MANUFACTURERS . " m
                INNER JOIN " . TABLE_PRODUCTS . " p
                    ON p.manufacturers_id = m.manufacturers_id
                   AND p.products_status = 1
          ORDER BY m.manufacturers_name, m.manufacturers_id"
    );
    while (!$r->EOF) {
        $id = (int)$r->fields['manufacturers_id'];
        $name = trim((string)$r->fields['manufacturers_name']);
        $master = (int)$r->fields['master_categories_id'];
        if ($name !== '' && ($master === 0 || isset($visibleCategories[$master]))) {
            if (!isset($brands[$id])) {
                $brands[$id] = ['id' => $id, 'name' => $name, 'count' => 0];
            }
            $brands[$id]['count']++;
        }
        $r->MoveNext();
    }
    return array_values($brands);
}

/**
 * Published EZ-Pages that appear somewhere on the storefront, in header order.
 *
 * `status_visible` is the published flag; a page nobody has put in the header,
 * a sidebox, the footer or the table of contents is left out too, since the
 * storefront offers no way to reach it. status_mobile is not consulted: it
 * does not exist on v1.5.8.
 *
 * @param object $db
 * @param int    $languageId
 * @return array
 */
function llmstxt_read_ezpages($db, $languageId)
{
    $pages = [];
    $r = $db->Execute(
        "SELECT e.pages_id, e.alt_url, e.alt_url_external, e.toc_chapter,
                e.header_sort_order, e.footer_sort_order, e.sidebox_sort_order,
                c.pages_title, c.pages_html_text
           FROM " . TABLE_EZPAGES . " e
                LEFT JOIN " . TABLE_EZPAGES_CONTENT . " c
                    ON c.pages_id = e.pages_id
                   AND c.languages_id = " . (int)$languageId . "
          WHERE e.status_visible = 1
            AND (e.status_header = 1 OR e.status_sidebox = 1 OR e.status_footer = 1 OR e.status_toc = 1)
          ORDER BY e.header_sort_order, e.footer_sort_order, e.sidebox_sort_order, c.pages_title"
    );
    while (!$r->EOF) {
        $title = trim((string)$r->fields['pages_title']);
        if ($title !== '') {
            $external = trim((string)$r->fields['alt_url_external']);
            $alt = trim((string)$r->fields['alt_url']);
            $id = (int)$r->fields['pages_id'];
            if ($external !== '') {
                $url = $external;
            } elseif ($alt !== '') {
                $url = llmstxt_link($alt);
            } else {
                $params = 'id=' . $id;
                if ((int)$r->fields['toc_chapter'] > 0) {
                    $params .= '&chapter=' . (int)$r->fields['toc_chapter'];
                }
                $url = llmstxt_link(llmstxt_cfg('FILENAME_EZPAGES', 'page'), $params);
            }
            $pages[] = [
                'id' => $id,
                'title' => $title,
                'url' => $url,
                'external' => ($external !== ''),
                'text' => (string)$r->fields['pages_html_text'],
            ];
        }
        $r->MoveNext();
    }
    return $pages;
}

/**
 * Labels for Zen Cart's built-in information pages, used when the owner has
 * not supplied one after a colon. Overridable by language constant.
 *
 * @return array
 */
function llmstxt_info_page_labels()
{
    return [
        'shippinginfo' => llmstxt_cfg('LLMSTXT_LABEL_SHIPPINGINFO', 'Shipping and Returns'),
        'privacy' => llmstxt_cfg('LLMSTXT_LABEL_PRIVACY', 'Privacy Notice'),
        'conditions' => llmstxt_cfg('LLMSTXT_LABEL_CONDITIONS', 'Conditions of Use'),
        'contact_us' => llmstxt_cfg('LLMSTXT_LABEL_CONTACT_US', 'Contact Us'),
        'site_map' => llmstxt_cfg('LLMSTXT_LABEL_SITE_MAP', 'Site Map'),
        'gv_faq' => llmstxt_cfg('LLMSTXT_LABEL_GV_FAQ', 'Gift Certificate FAQ'),
        'discount_coupon' => llmstxt_cfg('LLMSTXT_LABEL_DISCOUNT_COUPON', 'Discount Coupons'),
        'specials' => llmstxt_cfg('LLMSTXT_LABEL_SPECIALS', 'Specials'),
        'products_new' => llmstxt_cfg('LLMSTXT_LABEL_PRODUCTS_NEW', 'New Products'),
        'products_all' => llmstxt_cfg('LLMSTXT_LABEL_PRODUCTS_ALL', 'All Products'),
        'featured_products' => llmstxt_cfg('LLMSTXT_LABEL_FEATURED_PRODUCTS', 'Featured Products'),
        'reviews' => llmstxt_cfg('LLMSTXT_LABEL_REVIEWS', 'Customer Reviews'),
        'page_2' => 'Page 2',
        'page_3' => 'Page 3',
        'page_4' => 'Page 4',
    ];
}

/**
 * "shippinginfo, privacy, about_us:About Our Company" -> list of
 * ['page' => ..., 'label' => ..., 'url' => ...].
 *
 * A page name is restricted to the characters Zen Cart itself allows in
 * main_page, so nothing typed into the setting can reach a URL unencoded.
 *
 * @param string $text
 * @return array
 */
function llmstxt_info_pages($text)
{
    $labels = llmstxt_info_page_labels();
    $out = [];
    foreach (explode(',', (string)$text) as $entry) {
        $entry = trim($entry);
        if ($entry === '') {
            continue;
        }
        $label = '';
        $page = $entry;
        $colon = strpos($entry, ':');
        if ($colon !== false) {
            $page = trim(substr($entry, 0, $colon));
            $label = trim(substr($entry, $colon + 1));
        }
        $page = preg_replace('~[^0-9a-zA-Z_]~', '', $page);
        if ($page === '') {
            continue;
        }
        if ($label === '') {
            $label = $labels[$page] ?? ucwords(str_replace('_', ' ', $page));
        }
        $out[] = ['page' => $page, 'label' => $label, 'url' => llmstxt_link($page)];
    }
    return $out;
}

/**
 * The sitemap address: the configured one, else whichever common sitemap file
 * exists at the store root, else nothing.
 *
 * @param array $settings
 * @return string
 */
function llmstxt_sitemap_url(array $settings)
{
    if ($settings['sitemap'] !== '') {
        return $settings['sitemap'];
    }
    foreach (['sitemap.xml', 'sitemapindex.xml', 'sitemap_index.xml', 'sitemap.xml.gz'] as $file) {
        if (is_file(DIR_FS_CATALOG . $file)) {
            return llmstxt_catalog_base() . $file;
        }
    }
    return '';
}

/**
 * The address of robots.txt when the store has one, else ''. Listed so an
 * assistant that honors crawler directives knows where they are.
 *
 * @return string
 */
function llmstxt_robots_url()
{
    return is_file(DIR_FS_CATALOG . 'robots.txt') ? llmstxt_catalog_base() . 'robots.txt' : '';
}

/**
 * A short string that changes whenever the listable catalog changes.
 *
 * Aggregates only, so it is cheap enough to run from the storefront. A product
 * edit, add, delete or status change moves products_last_modified or the
 * count; the same for categories. EZ-Pages carry no timestamp, so only their
 * count is watched -- an edit to one is caught by the admin observer instead.
 *
 * @param object $db
 * @return string
 */
function llmstxt_fingerprint($db)
{
    $parts = [];

    $r = $db->Execute(
        "SELECT COUNT(*) AS n, MAX(products_last_modified) AS m, MAX(products_date_added) AS a
           FROM " . TABLE_PRODUCTS . "
          WHERE products_status = 1"
    );
    $parts[] = 'p' . (int)$r->fields['n'] . '|' . (string)$r->fields['m'] . '|' . (string)$r->fields['a'];

    $r = $db->Execute(
        "SELECT COUNT(*) AS n, MAX(last_modified) AS m, MAX(date_added) AS a
           FROM " . TABLE_CATEGORIES . "
          WHERE categories_status = 1"
    );
    $parts[] = 'c' . (int)$r->fields['n'] . '|' . (string)$r->fields['m'] . '|' . (string)$r->fields['a'];

    $r = $db->Execute(
        "SELECT COUNT(*) AS n, MAX(m.last_modified) AS m
           FROM " . TABLE_MANUFACTURERS . " m"
    );
    $f = is_array($r->fields) ? $r->fields : [];
    $parts[] = 'm' . (int)($f['n'] ?? 0) . '|' . (string)($f['m'] ?? '');

    $r = $db->Execute(
        "SELECT COUNT(*) AS n
           FROM " . TABLE_EZPAGES . "
          WHERE status_visible = 1"
    );
    $parts[] = 'e' . (int)$r->fields['n'];

    return sha1(implode(';', $parts));
}

/* ------------------------------------------------------------------ *
 * Rendering
 * ------------------------------------------------------------------ */

/**
 * Gather everything the two renderers need. One pass over the database.
 *
 * @param object     $db
 * @param array|null $settings
 * @return array
 */
function llmstxt_collect($db, $settings = null)
{
    if ($settings === null) {
        $settings = llmstxt_settings();
    }
    $languageId = llmstxt_language_id($db, $settings);

    $data = [
        'settings' => $settings,
        'language_id' => $languageId,
        // Configuration values are stored with HTML entities on some releases
        // ("Stoke &amp; Trent"), and this is a text file, not an HTML page.
        'store_name' => llmstxt_store_name(),
        'base_url' => llmstxt_catalog_base(),
        'currency' => llmstxt_default_currency($db),
        'currency_code' => (string)llmstxt_cfg('DEFAULT_CURRENCY', ''),
        'sitemap' => llmstxt_sitemap_url($settings),
        'robots' => llmstxt_robots_url(),
        'info_pages' => llmstxt_info_pages($settings['info_pages']),
        'categories' => [],
        'brands' => [],
        'products' => [],
        'ezpages' => [],
    ];

    $visible = [];
    if ($settings['categories'] || $settings['products'] || $settings['brands']) {
        $tree = llmstxt_category_tree(llmstxt_read_categories($db, $languageId), $settings);
        $visible = $tree['visible'];
        if ($settings['categories']) {
            $data['categories'] = $tree['list'];
        }
    }
    if ($settings['brands']) {
        $data['brands'] = llmstxt_read_brands($db, $visible);
    }
    if ($settings['products']) {
        $data['products'] = llmstxt_read_products($db, $languageId, $settings, $visible);
    }
    if ($settings['ezpages']) {
        $data['ezpages'] = llmstxt_read_ezpages($db, $languageId);
    }

    // Extension point: an observer may add to or change anything collected.
    llmstxt_notify('NOTIFY_LLMSTXT_COLLECT_END', $settings, $data);

    return $data;
}

/**
 * The store name for the H1. Configuration values can be stored with HTML
 * entities ("Stoke &amp; Trent"), and this is a text file, so they are
 * decoded. A store that has not set its name yet (the first build runs at
 * install time) gets its host name rather than an empty heading.
 *
 * @return string
 */
function llmstxt_store_name()
{
    $name = llmstxt_text(llmstxt_cfg('STORE_NAME', ''));
    if ($name !== '') {
        return $name;
    }
    $host = (string)parse_url(llmstxt_catalog_base(), PHP_URL_HOST);
    return $host !== '' ? $host : 'Online Store';
}

/**
 * A heading constant with a default, so a translation can rename any section.
 */
function llmstxt_heading($key, $default)
{
    $v = llmstxt_cfg($key, $default);
    return trim(str_replace(["\r", "\n"], ' ', (string)$v));
}

/**
 * The store's one-sentence summary for the blockquote.
 */
function llmstxt_summary(array $data)
{
    $summary = $data['settings']['summary'];
    if ($summary === '') {
        $summary = sprintf(llmstxt_cfg('LLMSTXT_DEFAULT_SUMMARY', '%s is an online store.'), $data['store_name']);
    }
    // One line, with any entities the admin editor stored turned back into
    // characters. Tags are left alone: the owner may want none, but this is
    // their text and Markdown tolerates inline HTML.
    $summary = html_entity_decode($summary, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    return trim(preg_replace('~\s+~', ' ', str_replace(["\r\n", "\r"], "\n", $summary)));
}

/**
 * Render llms.txt (or, with $full, llms-full.txt) from collected data.
 *
 * @param array $data  from llmstxt_collect()
 * @param bool  $full
 * @return string
 */
function llmstxt_render(array $data, $full = false)
{
    $s = $data['settings'];
    $out = [];

    $out[] = '# ' . llmstxt_label($data['store_name']);
    $out[] = '';
    $out[] = '> ' . llmstxt_summary($data);
    $out[] = '';

    if ($s['notes'] !== '') {
        // The owner's own Markdown, passed through as written apart from
        // undoing the entity encoding the admin editor may have applied.
        $out[] = trim(str_replace(["\r\n", "\r"], "\n", html_entity_decode($s['notes'], ENT_QUOTES | ENT_HTML5, 'UTF-8')));
        $out[] = '';
    }

    $out[] = llmstxt_item(llmstxt_heading('LLMSTXT_LABEL_WEBSITE', 'Website'), $data['base_url']);
    if ($data['currency_code'] !== '') {
        $out[] = '- ' . llmstxt_heading('LLMSTXT_LABEL_CURRENCY', 'Prices are in') . ': ' . llmstxt_label($data['currency_code']);
    }
    if ($data['sitemap'] !== '') {
        $out[] = llmstxt_item(llmstxt_heading('LLMSTXT_LABEL_SITEMAP', 'Sitemap'), $data['sitemap']);
    }
    if ($data['robots'] !== '') {
        $out[] = llmstxt_item(llmstxt_heading('LLMSTXT_LABEL_ROBOTS', 'Robots'), $data['robots']);
    }
    if (!$full && $s['full']) {
        $out[] = llmstxt_item(
            llmstxt_heading('LLMSTXT_LABEL_FULL', 'Full catalog listing'),
            $data['base_url'] . 'llms-full.txt',
            llmstxt_heading('LLMSTXT_NOTE_FULL', 'the same sections with complete descriptions')
        );
    }
    $out[] = '';

    if ($data['info_pages'] !== []) {
        $out[] = '## ' . llmstxt_heading('LLMSTXT_HEADING_INFO', 'Shopping information');
        $out[] = '';
        foreach ($data['info_pages'] as $page) {
            $out[] = llmstxt_item($page['label'], $page['url']);
        }
        $out[] = '';
    }

    if ($data['categories'] !== []) {
        $out[] = '## ' . llmstxt_heading('LLMSTXT_HEADING_CATEGORIES', 'Categories');
        $out[] = '';
        foreach ($data['categories'] as $c) {
            $url = llmstxt_link('index', 'cPath=' . $c['id']);
            $notes = llmstxt_text($c['description'], $full ? $s['full_length'] : $s['description_length']);
            $out[] = llmstxt_item($c['path'], $url, $notes);
        }
        $out[] = '';
    }

    if ($data['brands'] !== []) {
        $out[] = '## ' . llmstxt_heading('LLMSTXT_HEADING_BRANDS', 'Brands');
        $out[] = '';
        foreach ($data['brands'] as $b) {
            $url = llmstxt_link('index', 'manufacturers_id=' . $b['id']);
            $notes = ($b['count'] === 1)
                ? llmstxt_heading('LLMSTXT_NOTE_BRAND_ONE', '1 product')
                : sprintf(llmstxt_heading('LLMSTXT_NOTE_BRAND_MANY', '%d products'), $b['count']);
            $out[] = llmstxt_item($b['name'], $url, $notes);
        }
        $out[] = '';
    }

    if ($data['products'] !== []) {
        $out[] = '## ' . llmstxt_heading('LLMSTXT_HEADING_PRODUCTS', 'Products');
        $out[] = '';
        foreach ($data['products'] as $p) {
            $url = llmstxt_link($p['page'], 'products_id=' . $p['id']);
            $source = ($p['meta'] !== '') ? $p['meta'] : $p['description'];
            $notes = llmstxt_text($source, $full ? $s['full_length'] : $s['description_length']);
            $extras = [];
            if ($s['prices'] && $p['price'] > 0) {
                $extras[] = llmstxt_format_price($p['price'], $data['currency']);
            }
            if ($full && $p['model'] !== '') {
                $extras[] = llmstxt_heading('LLMSTXT_LABEL_MODEL', 'Model') . ' ' . $p['model'];
            }
            if ($extras !== []) {
                // Escaped once, with the rest of the notes, by llmstxt_item().
                $notes = ($notes === '' ? '' : $notes . ' ') . '(' . implode('; ', $extras) . ')';
            }
            $out[] = llmstxt_item($p['name'], $url, $notes);
        }
        $out[] = '';
    }

    if ($data['ezpages'] !== []) {
        $out[] = '## ' . llmstxt_heading('LLMSTXT_HEADING_PAGES', 'More pages');
        $out[] = '';
        foreach ($data['ezpages'] as $page) {
            $notes = $full ? llmstxt_text($page['text'], $s['full_length']) : '';
            $out[] = llmstxt_item($page['title'], $page['url'], $notes);
        }
        $out[] = '';
    }

    // Extension point: $out is the list of lines so far. The marker comment
    // is added afterwards so it always closes the file.
    llmstxt_notify('NOTIFY_LLMSTXT_RENDER_END', ['full' => $full, 'data' => $data], $out);

    $out[] = '<!-- ' . LLMSTXT_MARKER . ' ' . LLMSTXT_VERSION . ' on ' . gmdate('Y-m-d H:i') . ' UTC -->';

    return implode("\n", $out) . "\n";
}

/**
 * Collect and render in one call.
 *
 * @param object     $db
 * @param array|null $settings
 * @return array ['llms' => string, 'full' => string|null, 'fingerprint' => string, 'settings_hash' => string, 'counts' => array]
 */
function llmstxt_build($db, $settings = null)
{
    if ($settings === null) {
        $settings = llmstxt_settings();
    }
    $data = llmstxt_collect($db, $settings);
    return [
        'llms' => llmstxt_render($data, false),
        'full' => $settings['full'] ? llmstxt_render($data, true) : null,
        'fingerprint' => llmstxt_fingerprint($db),
        'settings_hash' => llmstxt_settings_hash($settings),
        'counts' => [
            'categories' => count($data['categories']),
            'brands' => count($data['brands']),
            'products' => count($data['products']),
            'ezpages' => count($data['ezpages']),
            'info_pages' => count($data['info_pages']),
        ],
    ];
}

/* ------------------------------------------------------------------ *
 * State, files, and the rebuild policy
 * ------------------------------------------------------------------ */

/**
 * The state file: when the last build ran, what it saw, and whether a change
 * has been flagged since. Lives in the cache directory, which Zen Cart already
 * requires to be writable, so it works on a store whose root is not.
 *
 * @return array
 */
function llmstxt_read_state()
{
    $defaults = [
        'built' => 0,
        'checked' => 0,
        'lock' => 0,
        'dirty' => false,
        'dirty_reason' => '',
        'fingerprint' => '',
        'settings_hash' => '',
        'file_sha1' => '',
        'full_sha1' => '',
        'takeover' => false,
        'last_error' => '',
        'last_reason' => '',
        'counts' => [],
    ];
    $path = llmstxt_state_path();
    if (!is_file($path)) {
        return $defaults;
    }
    $raw = (string)file_get_contents($path);
    // A byte-order mark, which an editor or a Windows tool may add, is not
    // JSON. Tolerated rather than treated as a corrupt file.
    if (strpos($raw, "\xEF\xBB\xBF") === 0) {
        $raw = substr($raw, 3);
    }
    $json = json_decode($raw, true);
    if (!is_array($json)) {
        return $defaults;
    }
    return array_merge($defaults, $json);
}

/**
 * @param array $state
 * @return bool
 */
function llmstxt_write_state(array $state)
{
    return llmstxt_write_file(llmstxt_state_path(), (string)json_encode($state, JSON_PRETTY_PRINT));
}

/**
 * Write a file in one step: to a temporary name first, then renamed over the
 * target, so a crawler never reads a half-written llms.txt.
 *
 * @param string $path
 * @param string $content
 * @return bool
 */
function llmstxt_write_file($path, $content)
{
    $dir = dirname($path);
    if (!is_dir($dir) || !is_writable($dir)) {
        return false;
    }
    if (is_file($path) && !is_writable($path)) {
        return false;
    }
    $tmp = $dir . '/.' . basename($path) . '.' . substr(sha1(uniqid('', true)), 0, 8) . '.tmp';
    if (file_put_contents($tmp, $content, LOCK_EX) === false) {
        return false;
    }
    // rename() over an existing file is atomic on POSIX; on Windows it can
    // refuse, so the target is removed first there and only there.
    if (!@rename($tmp, $path)) {
        if (is_file($path)) {
            @unlink($path);
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            return false;
        }
    }
    return true;
}

/**
 * Does a file at the store root belong to this plugin?
 *
 * Yes if its hash matches what the last build recorded, or if it carries the
 * marker line -- the second test survives a cleared cache directory. A file
 * that fails both was put there by somebody else and is never overwritten
 * unless the owner has said so from the admin page.
 *
 * @param string $path
 * @param array  $state
 * @param bool   $full
 * @return bool
 */
function llmstxt_file_is_ours($path, array $state, $full = false)
{
    if (!is_file($path)) {
        return true;
    }
    $content = (string)file_get_contents($path);
    $recorded = $full ? (string)$state['full_sha1'] : (string)$state['file_sha1'];
    if ($recorded !== '' && sha1($content) === $recorded) {
        return true;
    }
    return strpos($content, LLMSTXT_MARKER) !== false;
}

/**
 * A description of a file at the store root, for the admin page.
 *
 * @param bool  $full
 * @param array $state
 * @return array
 */
function llmstxt_file_status($full, array $state)
{
    $path = llmstxt_file_path($full);
    $exists = is_file($path);
    return [
        'path' => $path,
        'exists' => $exists,
        'ours' => $exists ? llmstxt_file_is_ours($path, $state, $full) : true,
        'size' => $exists ? (int)filesize($path) : 0,
        'modified' => $exists ? (int)filemtime($path) : 0,
        'writable' => $exists ? is_writable($path) : is_writable(dirname($path)),
    ];
}

/**
 * The rebuild interval for the timed policies, in seconds. 0 for the others.
 *
 * @param string $policy
 * @return int
 */
function llmstxt_policy_interval($policy)
{
    switch ($policy) {
        case 'daily':
            return 86400;
        case 'weekly':
            return 7 * 86400;
        case 'monthly':
            return 30 * 86400;
    }
    return 0;
}

/**
 * Should the storefront rebuild now? Returns the reason, or '' for no.
 *
 * Every policy rebuilds when nothing has ever been built, when a setting has
 * changed, or when the admin observer has flagged a change. The 'change'
 * policy also compares the catalog fingerprint; the timed policies wait for
 * their interval; 'manual' never rebuilds on its own.
 *
 * @param array       $state
 * @param array       $settings
 * @param string|null $fingerprint  pass null to skip the catalog comparison
 * @param int         $now
 * @return string
 */
function llmstxt_rebuild_reason(array $state, array $settings, $fingerprint, $now)
{
    if ((int)$state['built'] === 0) {
        return 'never built';
    }
    if ((string)$state['settings_hash'] !== llmstxt_settings_hash($settings)) {
        return 'settings changed';
    }
    if (!empty($state['dirty'])) {
        return 'catalog changed' . ((string)$state['dirty_reason'] !== '' ? ' (' . $state['dirty_reason'] . ')' : '');
    }
    if ($settings['rebuild'] === 'manual') {
        return '';
    }
    $interval = llmstxt_policy_interval($settings['rebuild']);
    if ($interval > 0) {
        return ((int)$state['built'] + $interval <= $now) ? 'scheduled (' . $settings['rebuild'] . ')' : '';
    }
    if ($fingerprint !== null && (string)$state['fingerprint'] !== (string)$fingerprint) {
        return 'catalog changed';
    }
    return '';
}

/**
 * Flag that the catalog has changed, from the admin observer. Cheap: one small
 * file write, no build. The next storefront check, or the next dynamic
 * request, does the work.
 *
 * @param string $reason
 * @return void
 */
function llmstxt_mark_dirty($reason = '')
{
    $state = llmstxt_read_state();
    if (!empty($state['dirty'])) {
        return;
    }
    $state['dirty'] = true;
    $state['dirty_reason'] = (string)$reason;
    llmstxt_write_state($state);
}

/**
 * Build and publish according to the settings.
 *
 * Writes the dynamic cache always (it is cheap, and it means the page never
 * has to build under a crawler), writes llms.txt and llms-full.txt when the
 * output setting says so, and records the result. A foreign file at the root
 * is left alone unless the owner has asked for it to be replaced.
 *
 * @param object $db
 * @param string $reason   recorded in the state for the admin page
 * @param bool   $takeover replace a file this plugin did not write
 * @return array ['ok' => bool, 'wrote' => [paths], 'skipped' => [messages], 'error' => string, 'counts' => array]
 */
function llmstxt_publish($db, $reason = 'manual', $takeover = false)
{
    $settings = llmstxt_settings();
    $state = llmstxt_read_state();
    $now = time();

    $result = ['ok' => true, 'wrote' => [], 'skipped' => [], 'error' => '', 'counts' => []];

    $state['lock'] = $now;
    llmstxt_write_state($state);

    try {
        $built = llmstxt_build($db, $settings);
    } catch (Throwable $e) {
        $state['lock'] = 0;
        $state['last_error'] = 'build failed: ' . $e->getMessage();
        llmstxt_write_state($state);
        return ['ok' => false, 'wrote' => [], 'skipped' => [], 'error' => $state['last_error'], 'counts' => []];
    }

    // The dynamic page's copy.
    if (!llmstxt_write_file(llmstxt_cache_path(false), $built['llms'])) {
        $result['skipped'][] = 'cache directory not writable: ' . llmstxt_cache_dir();
    }
    if ($built['full'] !== null) {
        llmstxt_write_file(llmstxt_cache_path(true), $built['full']);
    } elseif (is_file(llmstxt_cache_path(true))) {
        @unlink(llmstxt_cache_path(true));
    }

    // The published files.
    if ($settings['output'] === 'file' || $settings['output'] === 'both') {
        $targets = [[false, $built['llms']]];
        if ($built['full'] !== null) {
            $targets[] = [true, $built['full']];
        }
        foreach ($targets as $t) {
            [$full, $content] = $t;
            $path = llmstxt_file_path($full);
            if (!$takeover && !$state['takeover'] && !llmstxt_file_is_ours($path, $state, $full)) {
                $result['skipped'][] = basename($path) . ' was not written by this plugin and has been left alone';
                continue;
            }
            if (llmstxt_write_file($path, $content)) {
                $result['wrote'][] = $path;
                $state[$full ? 'full_sha1' : 'file_sha1'] = sha1($content);
            } else {
                $result['ok'] = false;
                $result['error'] = 'could not write ' . $path;
            }
        }
        // A full file left over from when the setting was on would go stale.
        if ($built['full'] === null && is_file(llmstxt_file_path(true))
            && llmstxt_file_is_ours(llmstxt_file_path(true), $state, true)
        ) {
            @unlink(llmstxt_file_path(true));
            $state['full_sha1'] = '';
        }
    }

    $state['built'] = $now;
    $state['checked'] = $now;
    $state['lock'] = 0;
    $state['dirty'] = false;
    $state['dirty_reason'] = '';
    $state['fingerprint'] = $built['fingerprint'];
    $state['settings_hash'] = $built['settings_hash'];
    $state['takeover'] = $takeover ? true : (bool)$state['takeover'];
    $state['last_error'] = $result['error'];
    $state['last_reason'] = (string)$reason;
    $state['counts'] = $built['counts'];
    llmstxt_write_state($state);

    $result['counts'] = $built['counts'];

    // Extension point: a build has just been published (or failed to be).
    llmstxt_notify('NOTIFY_LLMSTXT_PUBLISHED', ['reason' => (string)$reason, 'takeover' => (bool)$takeover], $result);

    return $result;
}

/**
 * Remove the files this plugin wrote to the store root. Files it did not
 * write are never touched.
 *
 * @return array  basenames removed
 */
function llmstxt_remove_files()
{
    $state = llmstxt_read_state();
    $removed = [];
    foreach ([false, true] as $full) {
        $path = llmstxt_file_path($full);
        if (is_file($path) && llmstxt_file_is_ours($path, $state, $full) && @unlink($path)) {
            $removed[] = basename($path);
            $state[$full ? 'full_sha1' : 'file_sha1'] = '';
        }
    }
    foreach ([llmstxt_cache_path(false), llmstxt_cache_path(true)] as $cache) {
        if (is_file($cache)) {
            @unlink($cache);
        }
    }
    $state['built'] = 0;
    llmstxt_write_state($state);
    return $removed;
}

/**
 * The storefront's periodic look at whether a published file needs rebuilding.
 *
 * Called from the init script on every page view, so it returns immediately
 * in the common case: the plugin is off, the output is dynamic-only, the last
 * look was recent, or another request is already building. Never throws.
 *
 * @param object $db
 * @return string  what happened, for the tests; '' when nothing did
 */
function llmstxt_maintain($db)
{
    try {
        $settings = llmstxt_settings();
        if (!$settings['enabled'] || $settings['output'] === 'dynamic') {
            return '';
        }
        $state = llmstxt_read_state();
        $now = time();
        if ((int)$state['lock'] > 0 && (int)$state['lock'] + LLMSTXT_LOCK_TTL > $now) {
            return 'locked';
        }
        if ((int)$state['checked'] + LLMSTXT_CHECK_INTERVAL > $now) {
            return '';
        }

        $fingerprint = ($settings['rebuild'] === 'change') ? llmstxt_fingerprint($db) : null;
        $reason = llmstxt_rebuild_reason($state, $settings, $fingerprint, $now);

        // The file itself may have been deleted by hand since the last build.
        if ($reason === '' && (int)$state['built'] > 0 && !is_file(llmstxt_file_path(false))) {
            $reason = 'file missing';
        }

        if ($reason === '') {
            $state['checked'] = $now;
            llmstxt_write_state($state);
            return '';
        }

        llmstxt_publish($db, 'storefront: ' . $reason);
        return 'rebuilt: ' . $reason;
    } catch (Throwable $e) {
        // A maintenance failure must never take a storefront page down.
        return 'error: ' . $e->getMessage();
    }
}

/**
 * The body for a dynamic request, building first if the cached copy is
 * missing or due for a rebuild.
 *
 * @param object $db
 * @param bool   $full
 * @return array ['status' => int, 'body' => string]
 */
function llmstxt_serve($db, $full = false)
{
    $settings = llmstxt_settings();
    if (!$settings['enabled']) {
        return ['status' => 404, 'body' => ''];
    }
    if ($full && !$settings['full']) {
        return ['status' => 404, 'body' => ''];
    }

    $state = llmstxt_read_state();
    $now = time();
    $cache = llmstxt_cache_path($full);

    $reason = '';
    if (!is_file($cache)) {
        $reason = 'cache missing';
    } elseif ((int)$state['lock'] > 0 && (int)$state['lock'] + LLMSTXT_LOCK_TTL > $now) {
        $reason = '';
    } elseif ((int)$state['checked'] + LLMSTXT_CHECK_INTERVAL <= $now) {
        $fingerprint = ($settings['rebuild'] === 'change') ? llmstxt_fingerprint($db) : null;
        $reason = llmstxt_rebuild_reason($state, $settings, $fingerprint, $now);
        if ($reason === '') {
            $state['checked'] = $now;
            llmstxt_write_state($state);
        }
    }

    if ($reason !== '') {
        llmstxt_publish($db, 'request: ' . $reason);
    }

    if (is_file($cache)) {
        $response = ['status' => 200, 'body' => (string)file_get_contents($cache)];
    } else {
        // The cache directory could not be written; build for this request alone.
        try {
            $built = llmstxt_build($db, $settings);
            $response = ['status' => 200, 'body' => $full ? (string)$built['full'] : $built['llms']];
        } catch (Throwable $e) {
            $response = ['status' => 500, 'body' => ''];
        }
    }

    // Extension point: the file is about to be sent to a visitor.
    llmstxt_notify('NOTIFY_LLMSTXT_SERVE', ['full' => $full, 'status' => $response['status']]);

    return $response;
}
